// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  idharaSidebar: [
    {
      type: 'doc',
      id: 'idhara/intro',
      label: 'Overview',
    },
    {
      type: 'category',
      label: 'Release Notes',
      items: [{ type: 'autogenerated', dirName: 'idhara/release-notes' }],
    },
    {
      type: 'category',
      label: 'User Manual',
      items: [{ type: 'autogenerated', dirName: 'idhara/user-manual' }],
    },
    {
      type: 'category',
      label: 'API Reference',
      items: [{ type: 'autogenerated', dirName: 'idhara/api' }],
    },
    {
      type: 'category',
      label: 'Firmware',
      items: [{ type: 'autogenerated', dirName: 'idhara/firmware' }],
    },
    {
      type: 'category',
      label: 'Mobile App',
      items: [{ type: 'autogenerated', dirName: 'idhara/mobile' }],
    },
    {
      type: 'category',
      label: 'Admin Dashboard',
      items: [{ type: 'autogenerated', dirName: 'idhara/admin' }],
    },
  ],

  apfcSidebar: [
    {
      type: 'doc',
      id: 'apfc/intro',
      label: 'Overview',
    },
    {
      type: 'category',
      label: 'Release Notes',
      items: [{ type: 'autogenerated', dirName: 'apfc/release-notes' }],
    },
    {
      type: 'category',
      label: 'User Manual',
      items: [{ type: 'autogenerated', dirName: 'apfc/user-manual' }],
    },
    {
      type: 'category',
      label: 'API Reference',
      items: [{ type: 'autogenerated', dirName: 'apfc/api' }],
    },
    {
      type: 'category',
      label: 'Firmware',
      items: [{ type: 'autogenerated', dirName: 'apfc/firmware' }],
    },
  ],

  orcSidebar: [
    {
      type: 'doc',
      id: 'orc/intro',
      label: 'Overview',
    },
    {
      type: 'category',
      label: 'Release Notes',
      items: [{ type: 'autogenerated', dirName: 'orc/release-notes' }],
    },
    {
      type: 'category',
      label: 'User Manual',
      items: [{ type: 'autogenerated', dirName: 'orc/user-manual' }],
    },
    {
      type: 'category',
      label: 'API Reference',
      items: [{ type: 'autogenerated', dirName: 'orc/api' }],
    },
    {
      type: 'category',
      label: 'Firmware',
      items: [{ type: 'autogenerated', dirName: 'orc/firmware' }],
    },
  ],

  demetercloudSidebar: [
    {
      type: 'doc',
      id: 'demetercloud/intro',
      label: 'Overview',
    },
    {
      type: 'category',
      label: 'Release Notes',
      items: [{ type: 'autogenerated', dirName: 'demetercloud/release-notes' }],
    },
    {
      type: 'category',
      label: 'API Reference',
      items: [{ type: 'autogenerated', dirName: 'demetercloud/api' }],
    },
    {
      type: 'category',
      label: 'User Manual',
      items: [{ type: 'autogenerated', dirName: 'demetercloud/user-manual' }],
    },
  ],
};

module.exports = sidebars;
